spring:
  datasource:
    url: jdbc:postgresql://10.16.239.43:5432/postgres # change this to your own jdbc url
    username: postgres  # change this to your own username (avoid using a superuser)
    password: Fs921012  # change this to your own password

    hikari:
      connection-timeout: 180000
      leak-detection-threshold: 120000

logging:
  level:
    root: off
    io.sustc: debug

---

benchmark:
  data-path: data
  student-mode: true
